version: "3.9"
services:
    mysql-db:
        image: mysql:8
        volumes: 
            - /home/defaultuser/docker/volumes/mysql-db:/var/lib/mysql
        networks: 
            - backend
        environment: 
            MYSQL_ROOT_PASSWORD: root
        ports: 
            - 3306:3306
            - 33060:33060
networks:
    backend:
